### ISSUE TITLE
希望支持组件导出UMD格式

### ISSUE THREAD

**Issue by nmy0808** [windlil/vuecomp-starter#1]
作者你好, 
希望可以支持组件导出UMD格式,
还想请教一个问题, 我想用element-plus进行二次封装怎么导入这个库呀

**Comment by windlil** [comment]
现在已经支持UMD打包了，把这段注释放开就可以了。
比如要对 el-button 进行二次封装，可以在 `button/src/button.vue` 下单独导入组件：
``` vue
<script setup lang="ts">
import { ElButton } from 'element-plus'
</script>
```
然后在 `button/src/style/index.scss` 去单独引入对应的组件样式：
```scss
@import url('element-plus/theme-chalk/el-button.css');
@import url('element-plus/theme-chalk/base.css');
```
这样打包出来也是支持按需引入的

**Comment by windlil** [comment]
现在已经支持UMD打包了，把这段注释放开就可以了 `packages/components/vite.config.js`
![Snipaste_2023-11-22_17-07-46](https://github.com/windlil/vuecomp-starter/assets/109407691/7973b3de-9d02-43ba-b2c4-ff5d1b1aaffa)

UMD模式打包的时候就不能引入其他组件库，我目前只试了element-plus，打包过程会报错，还不清楚什么问题。
比如要对 el-button 进行二次封装，可以在 `button/src/button.vue` 下单独导入组件：
``` vue
<script setup lang="ts">
import { ElButton } from 'element-plus'
</script>
```
然后在 `button/src/style/index.scss` 去单独引入对应的组件样式：
```scss
@import url('element-plus/theme-chalk/el-button.css');
@import url('element-plus/theme-chalk/base.css');
```
这样打包出来也是支持按需引入的

**Comment by nmy0808** [comment]
谢谢, 谢谢 !

**Comment by ckbabby** [comment]
你好，我根据这个教程简单弄了一个测试组件发现引用的时候报错
